FROM airhacks/openliberty-kernel-dev
LABEL maintainer="Adam Bien, adam-bien.com" description="OpenLiberty Java EE 8"
COPY hsqldb.jar ${INSTALL_DIR}
COPY server.xml ${CONFIG}
COPY bootstrap.properties ${CONFIG}
